name: CHASMplus_jupyter
channels:
- bioconda
- conda-forge
- defaults
- r
dependencies:
- r
- r-essentials
- numpy
- scipy
- rpy2
- matplotlib
- pandas
- scikit-learn
- seaborn
- jupyter
- jupyterlab
- pip:
  - matplotlib-venn
